
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vandana
 */
public class LoanAssistant extends javax.swing.JFrame {
    
    private Object computePayment;

    double loan;
    double interest;    
    double month;
    double payment;
    double monthlyPayments;
    private boolean computbutton;
    
    public LoanAssistant() {
        initComponents();
        Analysisbutton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        balancefield = new javax.swing.JTextField();
        Interestfield = new javax.swing.JTextField();
        Monthfield = new javax.swing.JTextField();
        Paymentfield = new javax.swing.JTextField();
        Computebutton = new javax.swing.JButton();
        Analysisbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        exitbutton = new javax.swing.JButton();
        xMonthlyButton = new javax.swing.JButton();
        xpaymentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Loan Balance");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Interest Rate");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Number of Payment");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Loan Analysis");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setText("Monthly Payment");

        balancefield.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N

        Interestfield.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N

        Monthfield.setBackground(new java.awt.Color(255, 255, 153));
        Monthfield.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Monthfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthfieldActionPerformed(evt);
            }
        });

        Paymentfield.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Paymentfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentfieldActionPerformed(evt);
            }
        });

        Computebutton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Computebutton.setText("Compute Monthly Payment");
        Computebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputebuttonActionPerformed(evt);
            }
        });

        Analysisbutton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        Analysisbutton.setText("New Loan Analysis");
        Analysisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisbuttonActionPerformed(evt);
            }
        });

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        exitbutton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        xMonthlyButton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        xMonthlyButton.setText("X");
        xMonthlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMonthlyButtonActionPerformed(evt);
            }
        });

        xpaymentButton.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        xpaymentButton.setText("X");
        xpaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpaymentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Monthfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Paymentfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Interestfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xMonthlyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xpaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(balancefield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Analysisbutton)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Computebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbutton)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(balancefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Interestfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Monthfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(xMonthlyButton))
                                    .addComponent(jLabel5))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Computebutton)
                                    .addComponent(exitbutton))
                                .addGap(18, 18, 18)
                                .addComponent(Analysisbutton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Paymentfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xpaymentButton)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void AnalysisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisbuttonActionPerformed
        // TODO add your handling code here:
        balancefield.setText("");
        Interestfield.setText("");
        Paymentfield.setText("");
        textarea.setText("");
        Analysisbutton.setEnabled(false);
        Computebutton.setEnabled(true);
    }//GEN-LAST:event_AnalysisbuttonActionPerformed

    private void PaymentfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentfieldActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_PaymentfieldActionPerformed

    private void xMonthlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xMonthlyButtonActionPerformed
        // TODO add your handling code here:
        computePayment = false;
        xpaymentButton.setVisible(true);
        xMonthlyButton.setVisible(false);
        Monthfield.setEditable(false);
        Monthfield.setBackground(Color.YELLOW);
        Monthfield.setFocusable(false);
        Paymentfield.setEditable(true);
        Paymentfield.setBackground(Color.WHITE);
        Paymentfield.setFocusable(true);
        balancefield.requestFocus();
        Computebutton.setVisible(true);
    }//GEN-LAST:event_xMonthlyButtonActionPerformed

    private void ComputebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputebuttonActionPerformed
        // TODO add your handling code here:
        String iMonthlyButton = String.format(Monthfield.getText());
        if(balancefield.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must enter amount of Balance", 
                    "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }else{
            loan = Double.parseDouble(balancefield.getText());
            String Balance = String.format(balancefield.getText());
        }
        if(Interestfield.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must enter amount of interest", 
                    "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }else{
            interest = Double.parseDouble(Interestfield.getText());
            String Balance = String.format(balancefield.getText());
        }
        if(Paymentfield.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must enter amount of payment", 
                    "Loan System", JOptionPane.INFORMATION_MESSAGE);
        }else{
            payment = Double.parseDouble(Paymentfield.getText());
            String Balance = String.format(balancefield.getText());
        }
         payment = loan +((loan * interest)/100);
         monthlyPayments = payment / month;
         String payMonth  = String.format("%.2f",monthlyPayments);
         Monthfield.setText(payMonth);
         textarea.append("\t\n Loan Assistant Project:\n\n" + 
                "Amount of Loan:\t\t $" + loan + 
                "\n number of payment: \t\t $" + interest +
                "\n monthly payment: \t\t $" + month +
                "\n payment for month: \t\t $" + monthlyPayments+ 
                "\n total loan payment: \t\t $" + payment+
                "\n thanks for using loan system" );
        Analysisbutton.setEnabled(true);
        Computebutton.setEnabled(false);
        
        
        
    }//GEN-LAST:event_ComputebuttonActionPerformed

    private void MonthfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthfieldActionPerformed

    private void xpaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpaymentButtonActionPerformed
        // TODO add your handling code here:
        computbutton = true;
        xpaymentButton.setVisible(false);
        xMonthlyButton.setVisible(true);
        Monthfield.setEditable(false);
        Monthfield.setBackground(Color.WHITE);
        Monthfield.setFocusable(true);
        Paymentfield.setEditable(false);
        Paymentfield.setBackground(Color.YELLOW);
        Paymentfield.setFocusable(false);
        balancefield.requestFocus();
    }//GEN-LAST:event_xpaymentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAssistant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analysisbutton;
    private javax.swing.JButton Computebutton;
    private javax.swing.JTextField Interestfield;
    private javax.swing.JTextField Monthfield;
    private javax.swing.JTextField Paymentfield;
    private javax.swing.JTextField balancefield;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea;
    private javax.swing.JButton xMonthlyButton;
    private javax.swing.JButton xpaymentButton;
    // End of variables declaration//GEN-END:variables
}
